"""
Polybot Snipez — Settlement Reference

What the 5-minute crypto markets actually resolve from, and what we can
actually see. These are not the same thing, and this module exists so the
difference is never silently papered over.

The market text (read live from Gamma, e.g. btc-updown-5m-*):

    "This market will resolve to 'Up' if the time-weighted average price
     (TWAP) of Bitcoin, generated by Chainlink, of the time range specified
     in the title is greater than or equal to the price at the beginning of
     that range."
    "The resolution source for this market is ... the BTC/USD TWAP data
     stream available at https://data.chain.link/streams/btc-usd-twap-60s-streams"

Two things follow, and the first version of this bot got both wrong:

  1. The source is the Chainlink BTC/USD **TWAP-60s data stream**, not
     Binance spot. Measured 2026-09-17, Binance USDT spot ran a persistent
     +7 to +9 bps ABOVE the Chainlink on-chain USD feed on all four assets
     (~$65 on BTC). As a level it is simply a different number. As a
     *difference* over a 5-minute window the bias mostly cancels, leaving a
     few dollars of residual on BTC — usable as a proxy, never as the truth.

  2. The statistic is the **TWAP over the window** against the price at the
     start of the window — not the last price against the candle open. In a
     trending window those differ by roughly a factor of two, and always in
     the direction that flatters a naive "distance from strike" reading.

Providers, in descending order of fidelity:

  chainlink_stream  the actual resolution source. Requires Chainlink Data
                    Streams credentials (the API rejects an unauthenticated
                    call naming UserId / Timestamp / HmacSignature headers).
                    Unavailable unless configured — and it says so.
  chainlink_feed    the on-chain Chainlink aggregator on Polygon. Verified
                    reachable. Same oracle family and USD quote, but it is a
                    SPOT deviation/heartbeat feed (15-33s update lag
                    observed), not the TWAP-60s stream. A closer proxy; not
                    the reference.
  binance           the existing fast feed. Kept because it updates in
                    milliseconds and is genuinely useful as confirmation.
                    A proxy, labelled as one, everywhere it is recorded.

Nothing here ever reports an official reference value it did not get from
the official source.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field

import requests

import config
from logger import log

WINDOW_SECONDS = 300

# Chainlink Data Streams feed IDs, taken from each market's resolutionSource.
OFFICIAL_STREAMS = {
    "BTC": "btc-usd-twap-60s",
    "ETH": "eth-usd-twap-60s",
    "SOL": "sol-usd-twap-60s",
    "XRP": "xrp-usd-twap-60s",
}

# On-chain Chainlink aggregators on Polygon (spot feeds — NOT the TWAP stream).
POLYGON_AGGREGATORS = {
    "BTC": "0xc907E116054Ad103354f2D350FD2514433D57F6f",
    "ETH": "0xF9680D99D6C9589e2a93a78A04A279e509205945",
    "SOL": "0x10C8264C0935b3B9870013e057f330Ff3e9C56dC",
    "XRP": "0x785ba89291f676b5386652eB12b30cF361020694",
}

LATEST_ROUND_DATA = "0xfeaf968c"   # latestRoundData() selector


@dataclass
class Reading:
    """One reference reading. `available` is the only field that matters first."""
    asset: str
    available: bool = False
    value: float = 0.0
    source: str = "unavailable"
    reason: str = ""
    as_of: float = 0.0
    age: float = -1.0
    is_official: bool = False


@dataclass
class WindowStats:
    """Time-weighted statistics for one asset over one 5-minute window."""
    asset: str
    window_start: float = 0.0
    open_price: float = 0.0       # first price we observed in the window
    last_price: float = 0.0
    twap: float = 0.0             # time-weighted mean since our first sample
    samples: int = 0
    first_sample_at: float = 0.0
    _weighted: float = field(default=0.0, repr=False)
    _elapsed: float = field(default=0.0, repr=False)
    _last_ts: float = field(default=0.0, repr=False)

    @property
    def coverage(self) -> float:
        """Fraction of the 5-minute window our samples actually span (0-1).

        Anything well under 1.0 means we joined late and the TWAP is not
        comparable to the official one — the analysis needs to know that.
        """
        if not self.first_sample_at or not self.window_start:
            return 0.0
        span = self._last_ts - self.window_start
        return max(0.0, min(1.0, span / WINDOW_SECONDS)) if span > 0 else 0.0

    @property
    def twap_distance(self) -> float:
        """TWAP minus the window's opening price — the resolution statistic."""
        if not self.open_price or not self.twap:
            return 0.0
        return self.twap - self.open_price

    @property
    def spot_distance(self) -> float:
        """Last price minus the opening price — what the first version used."""
        if not self.open_price or not self.last_price:
            return 0.0
        return self.last_price - self.open_price

    def observe(self, price: float, now: float):
        if price <= 0:
            return
        if self.samples == 0:
            self.open_price = price
            self.first_sample_at = now
            self._last_ts = now
        else:
            dt = max(0.0, now - self._last_ts)
            # Trapezoid between samples; a price holds until the next tick.
            self._weighted += self.last_price * dt
            self._elapsed += dt
            self._last_ts = now
        self.last_price = price
        self.samples += 1
        self.twap = (self._weighted / self._elapsed) if self._elapsed > 0 else price


class SettlementReference:
    """
    Tracks, per asset and per 5-minute window, what the settlement reference
    is and what our proxies say.

    `observe()` is called from the strategy's tick with whatever the Binance
    feed currently reads; everything else is derived.
    """

    def __init__(self, binance_feed=None, http_get=None, rpc_post=None):
        self.binance_feed = binance_feed
        self._http_get = http_get or requests.get
        self._rpc_post = rpc_post or requests.post
        self._lock = threading.Lock()
        self._windows: dict[tuple, WindowStats] = {}     # (asset, window_start)
        self._chainlink_cache: dict[str, tuple] = {}     # asset -> (Reading, ts)
        self._chainlink_ttl = 5.0
        self._stream_warned = False

    # ── window tracking ──────────────────────────────────────────────────

    def window_start_for(self, end_time_epoch: float) -> float:
        return end_time_epoch - WINDOW_SECONDS

    def observe(self, asset: str, window_start: float, now: float | None = None):
        """Sample the proxy feed into this asset's current window."""
        now = time.time() if now is None else now
        price = self.binance_price(asset)
        if price <= 0:
            return
        key = (asset.upper(), round(window_start))
        with self._lock:
            stats = self._windows.get(key)
            if stats is None:
                stats = WindowStats(asset=asset.upper(), window_start=window_start)
                self._windows[key] = stats
                self._prune(now)
            stats.observe(price, now)

    def window(self, asset: str, window_start: float) -> WindowStats:
        key = (asset.upper(), round(window_start))
        with self._lock:
            return self._windows.get(key) or WindowStats(
                asset=asset.upper(), window_start=window_start
            )

    def _prune(self, now: float):
        stale = [k for k, w in self._windows.items()
                 if now - (w.window_start + WINDOW_SECONDS) > 1800]
        for k in stale:
            self._windows.pop(k, None)

    # ── proxies ──────────────────────────────────────────────────────────

    def binance_price(self, asset: str) -> float:
        if self.binance_feed is None:
            return 0.0
        try:
            return float(getattr(self.binance_feed.get(asset), "price", 0.0) or 0.0)
        except Exception:
            return 0.0

    def chainlink_feed_reading(self, asset: str) -> Reading:
        """
        On-chain Chainlink aggregator on Polygon. A closer proxy than Binance
        — same oracle family, USD quote — but a SPOT feed, not the TWAP-60s
        stream the market resolves from, so is_official stays False.
        """
        asset = asset.upper()
        if not config.S9099_CHAINLINK_FEED_ENABLED:
            return Reading(asset=asset, source="chainlink_feed",
                           reason="disabled (S9099_CHAINLINK_FEED_ENABLED=false)")
        addr = POLYGON_AGGREGATORS.get(asset)
        if not addr:
            return Reading(asset=asset, source="chainlink_feed",
                           reason=f"no aggregator known for {asset}")

        now = time.time()
        cached = self._chainlink_cache.get(asset)
        if cached and now - cached[1] < self._chainlink_ttl:
            return cached[0]

        reading = Reading(asset=asset, source="chainlink_feed")
        try:
            resp = self._rpc_post(
                config.POLYGON_RPC_URL,
                json={"jsonrpc": "2.0", "id": 1, "method": "eth_call",
                      "params": [{"to": addr, "data": LATEST_ROUND_DATA}, "latest"]},
                timeout=6,
            )
            raw = (resp.json().get("result") or "")[2:]
            if len(raw) >= 256:
                answer = int(raw[64:128], 16)
                updated_at = int(raw[192:256], 16)
                reading.value = answer / 1e8      # these feeds are 8-decimal
                reading.as_of = float(updated_at)
                reading.age = now - updated_at
                reading.available = reading.value > 0
                reading.reason = "" if reading.available else "zero answer"
            else:
                reading.reason = "malformed RPC result"
        except Exception as e:
            reading.reason = f"rpc error: {type(e).__name__}"
        self._chainlink_cache[asset] = (reading, now)
        return reading

    # ── the official reference ───────────────────────────────────────────

    def official_reading(self, asset: str) -> Reading:
        """
        The Chainlink Data Streams TWAP-60s value this market resolves from.

        Unavailable without Data Streams credentials: an unauthenticated call
        is rejected for missing UserId / Timestamp / HmacSignature headers.
        When it is unavailable this returns available=False and a reason —
        it never substitutes a proxy and calls it official.

        NOTE: the authenticated request path below has never been exercised
        (no credentials were available when it was written). If it is ever
        enabled and the shape is wrong, it fails closed to "unavailable",
        which is the same state as not configuring it at all.
        """
        asset = asset.upper()
        feed_id = OFFICIAL_STREAMS.get(asset, "")
        reading = Reading(asset=asset, source="chainlink_twap_60s_stream",
                          is_official=True)
        if not feed_id:
            reading.reason = f"no official stream id known for {asset}"
            return reading
        if not (config.CHAINLINK_STREAMS_USER_ID and config.CHAINLINK_STREAMS_SECRET):
            reading.reason = "chainlink_streams_credentials_not_configured"
            if not self._stream_warned:
                self._stream_warned = True
                log.warning(
                    "[9099] Official settlement reference (Chainlink TWAP-60s stream) is "
                    "UNAVAILABLE — no Data Streams credentials. Binance is recorded as a "
                    "labelled proxy only, and proxy data does not arm the threshold stop."
                )
            return reading

        try:
            import hashlib
            import hmac as _hmac

            path = f"/api/v1/reports/latest?feedID={feed_id}"
            ts_ms = str(int(time.time() * 1000))
            body_hash = hashlib.sha256(b"").hexdigest()
            to_sign = f"GET {path} {body_hash} {config.CHAINLINK_STREAMS_USER_ID} {ts_ms}"
            signature = _hmac.new(
                config.CHAINLINK_STREAMS_SECRET.encode(),
                to_sign.encode(), hashlib.sha256,
            ).hexdigest()
            resp = self._http_get(
                f"{config.CHAINLINK_STREAMS_URL}{path}",
                headers={
                    "Authorization": config.CHAINLINK_STREAMS_USER_ID,
                    "X-Authorization-Timestamp": ts_ms,
                    "X-Authorization-Signature-SHA256": signature,
                },
                timeout=6,
            )
            if resp.status_code != 200:
                reading.reason = f"stream http {resp.status_code}"
                return reading
            report = (resp.json() or {}).get("report", {})
            price = float(report.get("benchmarkPrice", 0) or 0)
            if price <= 0:
                reading.reason = "stream returned no benchmark price"
                return reading
            # Data Streams quote prices with 18 decimals.
            reading.value = price / 1e18 if price > 1e12 else price
            reading.as_of = float(report.get("observationsTimestamp", time.time()))
            reading.age = time.time() - reading.as_of
            reading.available = True
        except Exception as e:
            reading.reason = f"stream error: {type(e).__name__}"
        return reading

    # ── the snapshot every record uses ───────────────────────────────────

    def snapshot(self, asset: str, window_start: float) -> dict:
        """
        Everything we know about this asset's settlement picture right now,
        with the official and proxy numbers kept in separate fields.
        """
        asset = asset.upper()
        stats = self.window(asset, window_start)
        official = self.official_reading(asset)
        cl_feed = self.chainlink_feed_reading(asset)
        binance = self.binance_price(asset)

        # Which proxy is carrying the "distance" signal, and by what statistic.
        proxy_source = "binance_twap_proxy" if stats.samples else "none"
        note = ""
        if not official.available:
            note = f"official unavailable ({official.reason}); distance is a {proxy_source}"

        return {
            # proxy — fast, labelled, never called official
            "binance_price": round(binance, 6) if binance else 0,
            "binance_window_open": round(stats.open_price, 6),
            "binance_window_twap": round(stats.twap, 6),
            "binance_window_coverage": round(stats.coverage, 3),
            "binance_window_samples": stats.samples,
            "proxy_twap_distance": round(stats.twap_distance, 6),
            "proxy_spot_distance": round(stats.spot_distance, 6),
            "proxy_reference_source": proxy_source,

            # a closer proxy, when enabled — still not the resolution source
            "chainlink_feed_price": round(cl_feed.value, 6) if cl_feed.available else "",
            "chainlink_feed_age": round(cl_feed.age, 1) if cl_feed.available else "",
            "chainlink_feed_available": cl_feed.available,

            # the real thing
            "official_resolution_reference": (
                round(official.value, 6) if official.available else ""
            ),
            "official_reference_source": (
                official.source if official.available else "unavailable"
            ),
            "official_reference_available": official.available,
            "official_reference_reason": official.reason,
            "distance_from_official_reference": "",   # filled in below when we can
            "reference_note": note,
        }

    def distance_for_side(self, asset: str, window_start: float, side: str) -> tuple:
        """
        (favourable_distance, source, is_official) for one side of a market.

        Positive means the side is currently winning on whatever reference we
        have. The caller must check `is_official` before letting this drive a
        hard rule — a proxy may confirm, it may not decide.
        """
        stats = self.window(asset, window_start)
        official = self.official_reading(asset)
        if official.available and stats.open_price:
            # Official value against the window's opening price. Still not a
            # full TWAP-vs-open comparison unless the stream itself is the
            # TWAP, which it is for these markets.
            distance = official.value - stats.open_price
            source, is_official = official.source, True
        else:
            distance = stats.twap_distance
            source, is_official = "binance_twap_proxy", False
        favourable = distance if side == "Up" else -distance
        return favourable, source, is_official
